plugins {
    id 'java-library'
}

apply plugin: 'eclipse'

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    testImplementation libs.junit
    implementation project(':app.data')
    implementation ':gui'
}

java {
    modularity.inferModulePath = true
    toolchain {
        languageVersion = JavaLanguageVersion.of(15)
    }
}
